fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
      - id: commitizen

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cd rust && cargo fmt -- --check'
        language: rust
        files: \.rs$
        args: []

      - id: cargo-deny
        name: cargo deny check
        description: Check cargo dependencies
        entry: bash -c 'cd rust && cargo deny check -d'
        language: rust
        files: \.rs$
        args: []

      - id: typos
        name: typos
        description: check typo
        entry: bash -c 'cd rust && typos'
        language: rust
        files: \.*$
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: bash -c 'cd rust && cargo check --all'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: bash -c 'cd rust && cargo clippy --all-targets --all-features --tests --benches -- -D warnings'
        language: rust
        files: \.rs$
        pass_filenames: false
